# Generated by Django 5.2.9 on 2026-01-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0234_alter_shoppinglist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='voice_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_step_files', to='cookbook.userfile'),
        ),
        migrations.AlterField(
            model_name='step',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='step_files', to='cookbook.userfile'),
        ),
    ]
